from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FeatureDetail:
    title: str
    summary: str
    prerequisites: str
    workflow: str
    output: str
    method: str = ""
    use_case: str = ""


_EXPLICIT: dict[str, FeatureDetail] = {
    "new_project": FeatureDetail("New Project", "Creates a managed TGPAssure project with a versioned SQLite database and standard raw, derived, export and report folders.", "Choose a project name and writable parent folder.", "Creates the project database, applies all schema migrations, creates the folder structure and opens the project workspace.", "A portable .tgp-project database plus managed project folders."),
    "open_project": FeatureDetail("Open Project", "Opens an existing TGPAssure project and migrates older schemas safely when needed.", "A valid .tgp-project file.", "Validates the project, creates migration backups, applies pending migrations and restores workspace context.", "An active project workspace."),
    "save_project": FeatureDetail("Save Project", "Persists workspace state and safely checkpoints the active project database.", "An open project.", "Writes workspace state, checkpoints SQLite WAL data and stores a recovery snapshot in .autosave.", "Updated project state and autosave snapshot."),
    "import_file": FeatureDetail("Import File", "Imports data into the managed project instead of only referencing an external path.", "An open project and a readable source file.", "Copies the file into the correct raw-data folder, streams a SHA-256 checksum, registers metadata in the project database and refreshes project state.", "A managed, traceable project file record."),
    "export_data": FeatureDetail("Export Project Inventory", "Exports a project inventory for audit, handoff and review.", "An open project.", "Reads registered project files and exports their module, role, size, checksum and paths to CSV or JSON.", "CSV or JSON project inventory."),
    "qc_history": FeatureDetail("QC History", "Shows persisted QC runs, stage results and findings across supported geophysical modules.", "An open project with at least one stored QC run for meaningful results.", "Queries project QC history and presents run status, scores, findings and timestamps.", "Auditable QC history."),
    "gravity_reduce": FeatureDetail("Standard Gravity Reduction", "Runs the standard land-gravity reduction chain while preserving the observed gravity channel.", "Gravity observations; latitude and elevation improve physical corrections. Base data improves drift correction.", "Applies/interpolates tide and drift corrections, normal gravity, free-air correction, Bouguer slab correction and terrain correction when available.", "Corrected channels including free-air, simple Bouguer and complete Bouguer anomaly."),
    "electrical_pseudosection": FeatureDetail("Electrical Pseudosection", "Displays measured apparent-resistivity or IP data as a pseudosection.", "Loaded electrical observations with usable electrode geometry or profile coordinates.", "Maps measured values to pseudodepth/display coordinates. It does not perform inversion.", "An apparent-data pseudosection for QC and interpretation support."),
    "geodetic_examiner": FeatureDetail("DC File Examiner", "Inspects geodetic survey/DC exchange records using selectable record families and fields while preserving source-line traceability.", "A readable DC/text/delimited survey export.", "Maps recognized record identifiers and semantic fields, keeps the original source line, and lets the reviewer include/exclude individual fields for text/Excel output.", "Auditable record-by-record geodetic metadata and observation inspection."),
    "geodetic_run_qc": FeatureDetail("Geodetic / GNSS QC", "Runs configurable GNSS survey-control screening for satellite geometry, DOP, precision, RMS, timing, positions, vectors and metadata completeness.", "A loaded geodetic/DC dataset; C6-style QC records enable the full metric set.", "Calculates metric distributions, checks configurable criteria, validates geographic bounds and GPS time intervals, and records evidence-backed findings.", "QC score, PASS/WARN/FAIL status, findings and four-graph QC pages.", method="PDOP/HDOP/VDOP, satellite count, RMS/SD/precision and GPS-week/time evidence are evaluated against editable project profiles; criteria are not treated as universally mandatory.", use_case="Use for survey-control QA/QC before accepting coordinates or delivering control/navigation data."),
    "visualization_load_volume": FeatureDetail("Load 3D Volume", "Loads supported seismic volume data for inline, crossline and time-slice visualization.", "An active seismic visualization workspace and a supported volume.", "Reads volume geometry and samples, builds the internal volume representation and enables 3D slice tools.", "Interactive 3D seismic volume views."),
    "segd_scanner_open": FeatureDetail("SEG-D / 428 Header Scanner", "Batch-scans SEG-D/Sercel field records and summarizes header, channel-set, trace-extension and source metadata for field QC.", "A SEG-D candidate file or folder.", "Attempts native SEG-D indexing first, then falls back to safe header-byte/ASCII inspection for unsupported legacy files.", "CSV-ready file audit with format, traces, sample interval, source, timebreak, uphole and warning status.", use_case="Use before processing to find wrong format, missing trace/header metadata, receiver-extension issues and suspicious field files."),
    "receiver_open": FeatureDetail("Receiver SMT QC", "Imports SMT-200/SMT-300 geophone/string tester exports and evaluates resistance, noise, frequency, damping, distortion, sensitivity, impedance and polarity.", "CSV/TXT/TSV tester export or converted SMT file.", "Maps vendor column aliases to receiver-QC fields, applies editable limits, groups failures and exports audit rows.", "Pass/warn/fail receiver QC table with failure categories and duplicate serial/string checks.", use_case="Use for geophone/string acceptance before spread deployment or repair decisions."),
    "uphole_open": FeatureDetail("Uphole QC & Interpretation", "Loads SEG-2/OYO/table uphole records, manages depth assignment and first-break picks, and builds time-depth/velocity results.", "SEG-2/OYO files or a depth-pick table.", "Imports metadata/picks, lets users edit depth and corrected time, then calculates interval velocities between valid time-depth points.", "Time-depth curve, layer velocity table and exportable interpretation CSV.", use_case="Use for weathering/static-control support and uphole delivery review."),
    "vibroseis_load_vaps": FeatureDetail("VAPS / H26 Field Vib QC", "Imports verbose vibrator attribute records and checks drive, phase, distortion, force warnings, overloads and HDOP by vibrator/VP.", "A VAPS/H26 CSV/TXT/ASCII export.", "Maps field-attribute columns, applies source-QC thresholds and groups bad vibrator/VP warning categories.", "VAPS field QC table with vib number, VP, phase, distortion, drive, warnings and status.", use_case="Use for daily vibrator fleet QC and maintenance prioritization."),
}


def _generic(action_id: str, label: str | None = None) -> FeatureDetail:
    clean = (label or action_id.replace("_", " ")).strip().title()
    prefix = action_id.split("_", 1)[0]
    module_names = {
        "segd": "SEG-D", "segy": "SEG-Y", "magnetic": "Magnetic",
        "gravity": "Gravity", "electrical": "Electrical",
        "visualization": "2D/3D Seismic", "seismic": "Seismic",
        "converter": "SEG-Y/SEG-D Converter", "vibroseis": "Vibroseis",
        "geodetic": "Geodetic / GNSS", "receiver": "Receiver / SMT",
        "receiver_qc": "Receiver / SMT", "uphole": "Uphole", "segd_scanner": "SEG-D Header Scanner",
    }
    module = module_names.get(prefix, "TGPAssure")
    if "agc" in action_id:
        return FeatureDetail(clean, "Applies automatic gain control for display/QC without modifying the raw source file.", "Loaded seismic traces and a valid time sample interval.", "Computes a moving RMS amplitude envelope and divides each valid sample by the local RMS, with safeguards against zero energy.", "Gain-adjusted display samples.", method="RMS(t)=sqrt(mean(x^2)) over the selected window; y(t)=x(t)/max(RMS(t), epsilon).", use_case="Use to reveal weak and strong events on the same display; do not use AGC amplitudes for true-amplitude interpretation.")
    if "fft" in action_id or "frequency" in action_id:
        return FeatureDetail(clean, f"Performs frequency-domain analysis in the {module} workflow.", "A loaded numeric signal with a known sample interval.", "Removes the mean, applies a taper where appropriate, computes a real FFT and maps spectral bins using the physical sample interval.", "Frequency spectrum and derived spectral metrics.", method="f_k=k/(N*dt); amplitude is derived from |FFT(x*w)| with window normalization.", use_case="Use for bandwidth, dominant-frequency, noise and source-response assessment.")
    if any(t in action_id for t in ("map", "geometry")):
        return FeatureDetail(clean, f"Displays spatial {module} geometry using decoded/scaled coordinates.", "Loaded data containing valid coordinates or receiver line/point geometry.", "Filters non-finite coordinates, preserves coordinate aspect ratio, calculates extents, path length and azimuth statistics, and plots source/receiver/midpoint positions.", "Interactive plan-view geometry map and geometry statistics.", method="Distance=sqrt(dx^2+dy^2); azimuth=atan2(dx,dy) converted to degrees clockwise from north.", use_case="Use to verify navigation, survey layout, line continuity, coverage and gross coordinate errors before interpretation.")
    if "volume" in action_id or "3d" in action_id:
        return FeatureDetail(clean, "Builds or displays a 3D seismic volume/curtain with inline, crossline and time/depth axes.", "SEG-Y inline/crossline geometry for a true volume; 2D/SEG-D data can be shown as a curtain.", "Indexes traces by inline/crossline, decimates only for interactive performance, preserves sample timing, robustly scales amplitudes and renders volume/slices with GPU acceleration when available.", "Interactive volume, inline/crossline slices and time slices.", method="Trace samples are mapped to V[inline,crossline,sample]. Missing cells remain distinguishable from valid amplitudes; display scaling uses robust percentiles rather than altering raw data.", use_case="Use for structural continuity, horizon/fault context, slice QC and spatial interpretation support.")
    if any(token in action_id for token in ("run_qc", "full_qc", "field_qc", "final_qc")):
        return FeatureDetail(clean, f"Runs the selected {module} quality-control workflow.", "Load the required source data first; some stages require base/reference or geometry data.", "Validates inputs, executes enabled QC stages, computes metrics/findings and persists the run when a project database is active.", "QC status, metrics, findings and report-ready results.", method="Stage-specific thresholds and robust statistics are applied to the actual measured/decoded channels.", use_case="Use before processing, interpretation or client delivery to identify data-quality risks.")
    if "report" in action_id or "pdf" in action_id or "xlsx" in action_id:
        return FeatureDetail(clean, f"Creates a report or export from the current {module} result state.", "A completed QC/processing/result state is required.", "Validates current results and writes the selected report format without changing raw data.", "A review/delivery report file.", method="Report values are derived from the active/persisted result objects; no synthetic measurements are introduced.", use_case="Use for audit trail, internal review and client deliverables.")
    if any(token in action_id for token in ("open", "import", "load")):
        return FeatureDetail(clean, f"Loads data into the {module} workflow.", "A supported readable source file or session.", "Validates the source, reads/indexes metadata and samples, and enables dependent tools only when prerequisites are present.", "Loaded data and an initialized workspace.", method="Large datasets are indexed/decimated for interactive display while raw source samples remain unchanged.", use_case="Use as the first step of the corresponding module workflow.")
    if any(token in action_id for token in ("export", "save")):
        return FeatureDetail(clean, f"Exports or saves the active {module} product.", "The corresponding data/result must exist.", "Validates the state and writes the selected product safely to the chosen destination.", "A persisted/exported file.", method="Derived outputs are written separately from original source files.", use_case="Use for handoff, archiving or downstream processing.")
    if any(token in action_id for token in ("grid", "profile", "histogram", "statistics", "cross_plot")):
        return FeatureDetail(clean, f"Creates a {module} analysis view from the active dataset.", "Load compatible data first.", "Uses the current measured/processed channels and physical axes to calculate the requested analysis.", "Interactive analysis and, where supported, exportable output.", method="Calculations use finite valid values and preserve units/coordinate timing metadata.", use_case="Use to interrogate trends, anomalies, distributions and QC relationships.")
    return FeatureDetail(clean, f"Executes {clean} in the {module} workspace.", "The action is enabled only when required data/state are available.", "TGPAssure validates prerequisites, performs the command and reports errors without overwriting raw source data.", "The corresponding workspace result or application action.", method="See the module controls and result metadata for operation-specific parameters.", use_case=f"Use when working in the {module} workflow and the stated prerequisite is satisfied.")

def get_feature_detail(action_id: str, label: str | None = None) -> FeatureDetail:
    return _EXPLICIT.get(action_id, _generic(action_id, label))
