from __future__ import annotations

import hashlib
import json
import os
import pickle
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Optional, TypeVar

T = TypeVar("T")


def _app_data_dir() -> Path:
    """Return the per-user TGPAssure data directory without requiring Qt."""
    root = os.environ.get("TGPASSURE_HOME")
    if root:
        base = Path(root).expanduser()
    else:
        base = Path.home() / ".tgpassure"
    base.mkdir(parents=True, exist_ok=True)
    return base


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


@dataclass(frozen=True)
class CacheStatus:
    hit: bool
    path: Path
    message: str


class FileCacheManager:
    """Small, safe, local cache for expensive file-open/index operations.

    The cache is invalidated when the source file path, byte size, modified time,
    or schema version changes.  It stores only trusted local data generated by
    TGPAssure under the current user's profile.
    """

    def __init__(self, root: str | Path | None = None) -> None:
        self.root = Path(root).expanduser() if root else _app_data_dir() / "cache"
        self.root.mkdir(parents=True, exist_ok=True)

    def get_or_compute(
        self,
        namespace: str,
        source_path: str | Path,
        producer: Callable[[], T],
        *,
        schema_version: str = "1",
        progress_callback: Optional[Callable[[int, str], None]] = None,
    ) -> tuple[T, CacheStatus]:
        source = Path(source_path).expanduser().resolve()
        cache_path = self._cache_path(namespace, source, schema_version)
        if progress_callback:
            progress_callback(8, f"Checking local cache for {source.name}")
        cached = self._read_cache(cache_path, source, schema_version)
        if cached is not None:
            if progress_callback:
                progress_callback(92, f"Loaded cached parsed/indexed data for {source.name}")
            return cached, CacheStatus(True, cache_path, "cache hit")
        if progress_callback:
            progress_callback(15, f"No valid cache found; parsing {source.name}")
        value = producer()
        self._write_cache(cache_path, source, schema_version, value)
        if progress_callback:
            progress_callback(88, f"Saved local cache for faster reopen of {source.name}")
        return value, CacheStatus(False, cache_path, "cache miss")


    def load(self, namespace: str, source_path: str | Path, *, schema_version: str = "1") -> tuple[Any | None, CacheStatus]:
        source = Path(source_path).expanduser().resolve()
        cache_path = self._cache_path(namespace, source, schema_version)
        value = self._read_cache(cache_path, source, schema_version)
        return value, CacheStatus(value is not None, cache_path, "cache hit" if value is not None else "cache miss")

    def store(self, namespace: str, source_path: str | Path, value: Any, *, schema_version: str = "1") -> CacheStatus:
        source = Path(source_path).expanduser().resolve()
        cache_path = self._cache_path(namespace, source, schema_version)
        self._write_cache(cache_path, source, schema_version, value)
        return CacheStatus(False, cache_path, "cache stored")

    def invalidate(self, namespace: str, source_path: str | Path, *, schema_version: str = "1") -> None:
        path = self._cache_path(namespace, Path(source_path).expanduser().resolve(), schema_version)
        try:
            path.unlink()
        except FileNotFoundError:
            pass

    def _cache_path(self, namespace: str, source: Path, schema_version: str) -> Path:
        safe_namespace = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in str(namespace)) or "general"
        folder = self.root / safe_namespace
        folder.mkdir(parents=True, exist_ok=True)
        stat = source.stat()
        token = json.dumps(
            {
                "path": str(source),
                "size": int(stat.st_size),
                "mtime_ns": int(stat.st_mtime_ns),
                "schema": str(schema_version),
            },
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        return folder / (hashlib.sha256(token).hexdigest() + ".tgp-cache")

    def _metadata(self, source: Path, schema_version: str) -> dict[str, Any]:
        stat = source.stat()
        return {
            "source_path": str(source),
            "source_name": source.name,
            "size": int(stat.st_size),
            "mtime_ns": int(stat.st_mtime_ns),
            "schema_version": str(schema_version),
            "created_at": _utc_now(),
        }

    def _read_cache(self, cache_path: Path, source: Path, schema_version: str) -> Any | None:
        if not cache_path.is_file():
            return None
        try:
            with cache_path.open("rb") as stream:
                payload = pickle.load(stream)
            metadata = payload.get("metadata", {}) if isinstance(payload, dict) else {}
            current = self._metadata(source, schema_version)
            for key in ("source_path", "size", "mtime_ns", "schema_version"):
                if metadata.get(key) != current.get(key):
                    return None
            return payload.get("value")
        except Exception:
            try:
                cache_path.unlink()
            except Exception:
                pass
            return None

    def _write_cache(self, cache_path: Path, source: Path, schema_version: str, value: Any) -> None:
        payload = {"metadata": self._metadata(source, schema_version), "value": value}
        tmp_fd, tmp_name = tempfile.mkstemp(prefix=cache_path.name, suffix=".tmp", dir=str(cache_path.parent))
        try:
            with os.fdopen(tmp_fd, "wb") as stream:
                pickle.dump(payload, stream, protocol=pickle.HIGHEST_PROTOCOL)
            Path(tmp_name).replace(cache_path)
        except Exception:
            try:
                os.unlink(tmp_name)
            except Exception:
                pass


class LocalActivityHistory:
    """Project-independent action history for opens, cache hits, QC runs and exports."""

    def __init__(self, root: str | Path | None = None) -> None:
        self.root = Path(root).expanduser() if root else _app_data_dir() / "history"
        self.root.mkdir(parents=True, exist_ok=True)
        self.path = self.root / "activity.jsonl"

    def record(
        self,
        *,
        module: str,
        action: str,
        file_path: str | Path | None = None,
        status: str = "success",
        details: Optional[dict[str, Any]] = None,
    ) -> None:
        try:
            source = Path(file_path).expanduser().resolve() if file_path else None
            row = {
                "timestamp": _utc_now(),
                "module": str(module or "general").lower(),
                "action": str(action or "action"),
                "status": str(status or "success"),
                "file_name": source.name if source else "",
                "file_path": str(source) if source else "",
                "details": details or {},
            }
            with self.path.open("a", encoding="utf-8") as stream:
                stream.write(json.dumps(row, ensure_ascii=False, default=str) + "\n")
        except Exception:
            # History must never break geophysical processing.
            return

    def list(self, *, module: str | None = None, limit: int = 1000) -> list[dict[str, Any]]:
        if not self.path.is_file():
            return []
        rows: list[dict[str, Any]] = []
        try:
            with self.path.open("r", encoding="utf-8") as stream:
                for line in stream:
                    try:
                        item = json.loads(line)
                    except Exception:
                        continue
                    if module and module.lower() not in {"all", "*"}:
                        if str(item.get("module") or "").lower() != module.lower():
                            continue
                    rows.append(item)
        except Exception:
            return []
        rows.sort(key=lambda r: str(r.get("timestamp") or ""), reverse=True)
        return rows[: max(1, int(limit))]
