from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Iterable


@dataclass(frozen=True)
class SegyQcProfile:
    key: str
    name: str
    description: str
    version: str
    thresholds: Dict[str, float]

    def with_overrides(self, overrides: Dict[str, Any] | None = None) -> "SegyQcProfile":
        merged = dict(self.thresholds)
        for key, value in (overrides or {}).items():
            if key in merged:
                merged[key] = float(value)
        return SegyQcProfile(
            key=self.key,
            name=self.name,
            description=self.description,
            version=self.version,
            thresholds=merged,
        )


_BASE_THRESHOLDS: Dict[str, float] = {
    "sample_interval_min_us": 100.0,
    "sample_interval_max_us": 16000.0,
    "samples_per_trace_min": 1.0,
    "samples_per_trace_max": 200000.0,
    "blank_text_header_max_pct": 65.0,
    "trace_header_ns_mismatch_max_pct": 0.10,
    "trace_header_dt_mismatch_max_pct": 0.10,
    "duplicate_trace_sequence_max_pct": 0.10,
    "invalid_trace_id_max_pct": 0.10,
    "missing_coordinate_max_pct": 2.0,
    "duplicate_coordinate_max_pct": 5.0,
    "coordinate_jump_mad_factor": 12.0,
    "fold_cv_max": 1.50,
    "zero_trace_max_pct": 0.50,
    "dead_trace_max_pct": 1.00,
    "dead_rms_ratio": 0.01,
    "noisy_trace_max_pct": 2.00,
    "noise_ratio_max": 1.65,
    "rms_outlier_mad_factor": 8.0,
    "clipped_trace_max_pct": 0.50,
    "clipping_plateau_min_pct": 1.00,
    "spike_trace_max_pct": 1.00,
    "spike_score_max": 18.0,
    "dc_bias_trace_max_pct": 1.00,
    "dc_bias_ratio_max": 0.20,
    "energy_outlier_max_pct": 2.00,
    "energy_outlier_mad_factor": 8.0,
    "dominant_frequency_min_hz": 1.0,
    "dominant_frequency_max_hz": 250.0,
    "bandwidth_min_hz": 8.0,
    "static_abs_max_ms": 1000.0,
    "static_outlier_max_pct": 1.0,
    "delay_time_abs_max_ms": 5000.0,
    "navigation_step_mad_factor": 12.0,
    "navigation_duplicate_max_pct": 5.0,
    "max_frequency_traces": 600.0,
    "max_context_trace_indices": 200.0,
    "residual_static_max_ms": 12.0,
    "residual_static_outlier_factor": 4.5,
    "velocity_min_m_s": 1200.0,
    "velocity_max_m_s": 6500.0,
    "semblance_min": 0.25,
    "velocity_smoothness_max": 20.0,
    "residual_moveout_max_ms": 12.0,
    "flatness_ratio_min": 0.75,
    "nmo_stretch_max_pct": 30.0,
    "snr_min_db": 6.0,
    "stack_coherence_min": 0.35,
    "amplitude_variation_max_pct": 40.0,
    "migration_artifact_max_pct": 8.0,
    "velocity_smoothness_min": 70.0,
    "migration_focus_ratio_min": 1.20,
    "coherence_min": 0.35,
    "phase_variation_max": 90.0,
    "attribute_outlier_factor": 6.0,
    "nrms_max": 60.0,
    "predictability_min": 0.70,
    "time_shift_max_ms": 8.0,
    "amplitude_ratio_min_max": 0.25,
}


def _scaled(**changes: float) -> Dict[str, float]:
    values = dict(_BASE_THRESHOLDS)
    values.update(changes)
    return values


PROFILES: Dict[str, SegyQcProfile] = {
    "standard": SegyQcProfile(
        key="standard",
        name="Standard SEG-Y QC",
        description="Balanced quality-control thresholds for routine SEG-Y review.",
        version="1.0",
        thresholds=_scaled(),
    ),
    "field": SegyQcProfile(
        key="field",
        name="Field Acquisition QC",
        description="Operational field profile that tolerates limited acquisition noise while protecting geometry and timing integrity.",
        version="1.0",
        thresholds=_scaled(
            zero_trace_max_pct=1.0,
            dead_trace_max_pct=2.0,
            noisy_trace_max_pct=4.0,
            clipped_trace_max_pct=1.0,
            spike_trace_max_pct=2.0,
            dc_bias_trace_max_pct=2.0,
            energy_outlier_max_pct=4.0,
            missing_coordinate_max_pct=1.0,
            trace_header_ns_mismatch_max_pct=0.05,
            trace_header_dt_mismatch_max_pct=0.05,
            residual_static_max_ms=20.0,
            residual_static_outlier_factor=6.0,
            velocity_min_m_s=800.0,
            velocity_max_m_s=7500.0,
            semblance_min=0.15,
            velocity_smoothness_max=35.0,
            residual_moveout_max_ms=25.0,
            flatness_ratio_min=0.55,
            nmo_stretch_max_pct=45.0,
            snr_min_db=3.0,
            stack_coherence_min=0.20,
            amplitude_variation_max_pct=65.0,
            migration_artifact_max_pct=15.0,
            velocity_smoothness_min=50.0,
            migration_focus_ratio_min=1.05,
            coherence_min=0.20,
            phase_variation_max=130.0,
            attribute_outlier_factor=8.0,
            nrms_max=90.0,
            predictability_min=0.50,
            time_shift_max_ms=16.0,
            amplitude_ratio_min_max=0.40,
        ),
    ),
    "processing": SegyQcProfile(
        key="processing",
        name="Processing Deliverable QC",
        description="Profile for processed seismic deliverables with stricter amplitude, frequency and header consistency checks.",
        version="1.0",
        thresholds=_scaled(
            zero_trace_max_pct=0.25,
            dead_trace_max_pct=0.50,
            noisy_trace_max_pct=1.0,
            clipped_trace_max_pct=0.25,
            spike_trace_max_pct=0.50,
            dc_bias_trace_max_pct=0.50,
            energy_outlier_max_pct=1.0,
            blank_text_header_max_pct=45.0,
            duplicate_trace_sequence_max_pct=0.05,
            residual_static_max_ms=8.0,
            residual_static_outlier_factor=4.0,
            velocity_min_m_s=1400.0,
            velocity_max_m_s=6000.0,
            semblance_min=0.30,
            velocity_smoothness_max=15.0,
            residual_moveout_max_ms=8.0,
            flatness_ratio_min=0.82,
            nmo_stretch_max_pct=25.0,
            snr_min_db=8.0,
            stack_coherence_min=0.45,
            amplitude_variation_max_pct=30.0,
            migration_artifact_max_pct=5.0,
            velocity_smoothness_min=80.0,
            migration_focus_ratio_min=1.30,
            coherence_min=0.45,
            phase_variation_max=60.0,
            attribute_outlier_factor=5.0,
            nrms_max=50.0,
            predictability_min=0.78,
            time_shift_max_ms=6.0,
            amplitude_ratio_min_max=0.20,
        ),
    ),
    "strict": SegyQcProfile(
        key="strict",
        name="Strict Client Delivery QC",
        description="Strict delivery profile intended for formal client submission and archival acceptance.",
        version="1.0",
        thresholds=_scaled(
            blank_text_header_max_pct=35.0,
            trace_header_ns_mismatch_max_pct=0.0,
            trace_header_dt_mismatch_max_pct=0.0,
            duplicate_trace_sequence_max_pct=0.0,
            invalid_trace_id_max_pct=0.0,
            missing_coordinate_max_pct=0.0,
            duplicate_coordinate_max_pct=1.0,
            zero_trace_max_pct=0.10,
            dead_trace_max_pct=0.25,
            noisy_trace_max_pct=0.50,
            clipped_trace_max_pct=0.10,
            spike_trace_max_pct=0.25,
            dc_bias_trace_max_pct=0.25,
            energy_outlier_max_pct=0.50,
            static_outlier_max_pct=0.25,
            residual_static_max_ms=5.0,
            residual_static_outlier_factor=3.5,
            velocity_min_m_s=1500.0,
            velocity_max_m_s=5500.0,
            semblance_min=0.35,
            velocity_smoothness_max=10.0,
            residual_moveout_max_ms=5.0,
            flatness_ratio_min=0.90,
            nmo_stretch_max_pct=20.0,
            snr_min_db=10.0,
            stack_coherence_min=0.55,
            amplitude_variation_max_pct=20.0,
            migration_artifact_max_pct=3.0,
            velocity_smoothness_min=85.0,
            migration_focus_ratio_min=1.40,
            coherence_min=0.55,
            phase_variation_max=45.0,
            attribute_outlier_factor=4.0,
            nrms_max=35.0,
            predictability_min=0.85,
            time_shift_max_ms=4.0,
            amplitude_ratio_min_max=0.15,
        ),
    ),
}


THRESHOLD_LABELS: Dict[str, str] = {
    "sample_interval_min_us": "Minimum sample interval (µs)",
    "sample_interval_max_us": "Maximum sample interval (µs)",
    "samples_per_trace_min": "Minimum samples per trace",
    "samples_per_trace_max": "Maximum samples per trace",
    "blank_text_header_max_pct": "Maximum blank textual-header lines (%)",
    "trace_header_ns_mismatch_max_pct": "Maximum trace sample-count mismatch (%)",
    "trace_header_dt_mismatch_max_pct": "Maximum trace sample-interval mismatch (%)",
    "duplicate_trace_sequence_max_pct": "Maximum duplicate trace sequence (%)",
    "invalid_trace_id_max_pct": "Maximum invalid trace identification (%)",
    "missing_coordinate_max_pct": "Maximum missing coordinate traces (%)",
    "duplicate_coordinate_max_pct": "Maximum duplicate receiver coordinates (%)",
    "coordinate_jump_mad_factor": "Coordinate jump robust-MAD factor",
    "fold_cv_max": "Maximum fold coefficient of variation",
    "zero_trace_max_pct": "Maximum zero traces (%)",
    "dead_trace_max_pct": "Maximum dead traces (%)",
    "dead_rms_ratio": "Dead-trace RMS ratio",
    "noisy_trace_max_pct": "Maximum noisy traces (%)",
    "noise_ratio_max": "Maximum trace noise ratio",
    "rms_outlier_mad_factor": "RMS robust-MAD factor",
    "clipped_trace_max_pct": "Maximum clipped traces (%)",
    "clipping_plateau_min_pct": "Clipping plateau minimum (%)",
    "spike_trace_max_pct": "Maximum spiky traces (%)",
    "spike_score_max": "Maximum spike score",
    "dc_bias_trace_max_pct": "Maximum DC-biased traces (%)",
    "dc_bias_ratio_max": "Maximum DC-bias/RMS ratio",
    "energy_outlier_max_pct": "Maximum energy outlier traces (%)",
    "energy_outlier_mad_factor": "Energy robust-MAD factor",
    "dominant_frequency_min_hz": "Minimum dominant frequency (Hz)",
    "dominant_frequency_max_hz": "Maximum dominant frequency (Hz)",
    "bandwidth_min_hz": "Minimum spectral bandwidth (Hz)",
    "static_abs_max_ms": "Maximum absolute total static (ms)",
    "static_outlier_max_pct": "Maximum static outliers (%)",
    "delay_time_abs_max_ms": "Maximum absolute delay time (ms)",
    "navigation_step_mad_factor": "Navigation step robust-MAD factor",
    "navigation_duplicate_max_pct": "Maximum duplicate navigation points (%)",
    "max_frequency_traces": "Maximum traces used for spectral QC",
    "max_context_trace_indices": "Maximum trace references stored per finding",
    "residual_static_max_ms": "Maximum residual static magnitude (ms)",
    "residual_static_outlier_factor": "Residual-static robust-MAD outlier factor",
    "velocity_min_m_s": "Minimum accepted RMS velocity (m/s)",
    "velocity_max_m_s": "Maximum accepted RMS velocity (m/s)",
    "semblance_min": "Minimum accepted velocity semblance",
    "velocity_smoothness_max": "Maximum adjacent velocity change, 95th percentile (%)",
    "residual_moveout_max_ms": "Maximum residual moveout after NMO (ms)",
    "flatness_ratio_min": "Minimum gather-flatness ratio",
    "nmo_stretch_max_pct": "Maximum NMO stretch, 95th percentile (%)",
    "snr_min_db": "Minimum brute-stack signal-to-noise ratio (dB)",
    "stack_coherence_min": "Minimum pre-stack coherence for stacking",
    "amplitude_variation_max_pct": "Maximum stack RMS amplitude variation (%)",
    "migration_artifact_max_pct": "Maximum migration-artifact coverage (%)",
    "velocity_smoothness_min": "Minimum migration-velocity smoothness score (%)",
    "migration_focus_ratio_min": "Minimum migration focusing ratio",
    "coherence_min": "Minimum post-stack attribute coherence",
    "phase_variation_max": "Maximum lateral instantaneous-phase spread (degrees)",
    "attribute_outlier_factor": "Post-stack attribute robust-MAD outlier factor",
    "nrms_max": "Maximum 4D normalized RMS difference (%)",
    "predictability_min": "Minimum 4D base/monitor predictability",
    "time_shift_max_ms": "Maximum 4D base/monitor time shift (ms)",
    "amplitude_ratio_min_max": "Maximum 4D amplitude-ratio deviation from unity",
}


def get_profile(key: str, overrides: Dict[str, Any] | None = None) -> SegyQcProfile:
    profile = PROFILES.get(key)
    if profile is None:
        raise KeyError(f"Unknown SEG-Y QC profile: {key}")
    return profile.with_overrides(overrides)


def list_profiles() -> Iterable[SegyQcProfile]:
    return PROFILES.values()
